#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate project-local Zephyr USB overrides without modifying ZEPHYR_BASE.

The generated sources are derived from the Zephyr files in --zephyr-base and
written under the build directory. They carry the original source file license
headers because this script transforms the full source text.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


def add_provenance_banner(text: str, source: Path) -> str:
    banner = (
        "/*\n"
        " * Generated by scripts/generate_zephyr_overrides.py. Do not edit.\n"
        f" * Source: {source}\n"
        " * Reason: project-local Titan UVC repeated-preview override without modifying ZEPHYR_BASE.\n"
        " */\n\n"
    )
    return replace_once(
        text,
        " * SPDX-License-Identifier: Apache-2.0\n */\n\n",
        " * SPDX-License-Identifier: Apache-2.0\n */\n\n" + banner,
        f"{source}: provenance banner insertion",
    )


def patch_uvc(src: str) -> str:
    src = replace_once(
        src,
        "static void uvc_flush_queue(const struct device *dev);\n",
        "static void uvc_flush_queue(const struct device *dev);\n"
        "static void uvc_return_vbuf(const struct device *dev, struct video_buffer *vbuf);\n"
        "static void uvc_reset_queued_vbufs(const struct device *dev);\n",
        "uvc forward declarations",
    )

    src = replace_once(
        src,
        "\tif (atomic_test_bit(&data->state, UVC_STATE_STREAM_READY)) {\n"
        "\t\tatomic_set_bit(&data->state, UVC_STATE_STREAM_RESTART);\n"
        "\t}\n\n"
        "\tatomic_set_bit(&data->state, UVC_STATE_STREAM_READY);\n"
        "\tuvc_flush_queue(dev);\n",
        "\tif (atomic_test_bit(&data->state, UVC_STATE_STREAM_READY)) {\n"
        "\t\tuvc_reset_queued_vbufs(dev);\n"
        "\t}\n\n"
        "\tatomic_clear_bit(&data->state, UVC_STATE_PAUSED);\n"
        "\tatomic_set_bit(&data->state, UVC_STATE_STREAM_READY);\n"
        "\tuvc_flush_queue(dev);\n",
        "uvc commit restart handling",
    )

    src = replace_once(
        src,
        "\tstruct net_buf *buf;\n"
        "\t/* Workaround net_buf that uses uint16_t storage for lengths and offsets */\n"
        "\tconst size_t max_len = 0xf000;\n"
        "\tconst size_t buf_len = MIN(max_len, vbuf->bytesused - data->vbuf_offset);\n\n"
        "\t/* Directly pass the vbuf content with zero-copy */\n"
        "\tbuf = net_buf_alloc_with_data(&uvc_buf_pool, vbuf->buffer + data->vbuf_offset,\n"
        "\t\t\t\t      buf_len, K_NO_WAIT);\n"
        "\tif (buf == NULL) {\n"
        "\t\tLOG_DBG(\"Cannot allocate continuation USB buffer for now\");\n"
        "\t\treturn NULL;\n"
        "\t}\n\n"
        "\t/* If uncompressed and line-based format, update the next line position in the frame */\n",
        "\tstruct net_buf *buf;\n"
        "\tconst size_t max_len = 8192;\n"
        "\tconst size_t buf_len = MIN(max_len, vbuf->bytesused - data->vbuf_offset);\n\n"
        "\tbuf = net_buf_alloc_len(&uvc_buf_pool, buf_len, K_NO_WAIT);\n"
        "\tif (buf == NULL) {\n"
        "\t\tLOG_DBG(\"Cannot allocate continuation USB buffer for now\");\n"
        "\t\treturn NULL;\n"
        "\t}\n\n"
        "\tnet_buf_add_mem(buf, vbuf->buffer + data->vbuf_offset, buf_len);\n\n"
        "\t/* If uncompressed and line-based format, update the next line position in the frame */\n",
        "uvc copied continuation payload",
    )

    src = replace_once(
        src,
        "\tif (next_vbuf_offset == vbuf->bytesused) {\n"
        "\t\tbi->vbuf = vbuf;\n"
        "\t\tbi->udc.zlp = (buf->len % uvc_get_bulk_mps(cfg->c_data) == 0);\n"
        "\t}\n",
        "\tif (next_vbuf_offset == vbuf->bytesused) {\n"
        "\t\tbi->vbuf = NULL;\n"
        "\t\tbi->udc.zlp = (buf->len % uvc_get_bulk_mps(cfg->c_data) == 0);\n"
        "\t}\n",
        "uvc disable completion vbuf ownership",
    )

    src = replace_once(
        src,
        "static void uvc_flush_queue(const struct device *dev)\n"
        "{\n",
        "static void uvc_return_vbuf(const struct device *dev, struct video_buffer *vbuf)\n"
        "{\n"
        "\tstruct uvc_data *data = dev->data;\n\n"
        "\tk_fifo_put(&data->fifo_out, vbuf);\n\n"
        "\tif (IS_ENABLED(CONFIG_POLL) && data->video_sig != NULL) {\n"
        "\t\tk_poll_signal_raise(data->video_sig, VIDEO_BUF_DONE);\n"
        "\t}\n"
        "}\n\n"
        "static void uvc_return_queued_vbufs(const struct device *dev)\n"
        "{\n"
        "\tstruct uvc_data *data = dev->data;\n"
        "\tstruct video_buffer *vbuf;\n\n"
        "\t__ASSERT_NO_MSG(!k_is_in_isr());\n\n"
        "\tk_mutex_lock(&data->mutex, K_FOREVER);\n\n"
        "\tif (data->vbuf_offset == 0) {\n"
        "\t\twhile ((vbuf = k_fifo_get(&data->fifo_in, K_NO_WAIT)) != NULL) {\n"
        "\t\t\tuvc_return_vbuf(dev, vbuf);\n"
        "\t\t}\n"
        "\t}\n\n"
        "\tk_mutex_unlock(&data->mutex);\n"
        "}\n\n"
        "static void uvc_reset_queued_vbufs(const struct device *dev)\n"
        "{\n"
        "\tstruct uvc_data *data = dev->data;\n"
        "\tstruct video_buffer *vbuf;\n\n"
        "\t__ASSERT_NO_MSG(!k_is_in_isr());\n\n"
        "\tk_mutex_lock(&data->mutex, K_FOREVER);\n\n"
        "\tdata->vbuf_offset = 0;\n"
        "\tatomic_clear_bit(&data->state, UVC_STATE_STREAM_RESTART);\n"
        "\twhile ((vbuf = k_fifo_get(&data->fifo_in, K_NO_WAIT)) != NULL) {\n"
        "\t\tuvc_return_vbuf(dev, vbuf);\n"
        "\t}\n\n"
        "\tk_mutex_unlock(&data->mutex);\n"
        "}\n\n"
        "static void uvc_flush_queue(const struct device *dev)\n"
        "{\n",
        "uvc return helpers",
    )

    src = replace_once(
        src,
        "\t\tif (ret == UVC_VBUF_DONE) {\n"
        "\t\t\tLOG_DBG(\"Video buffer %p transferred, removing from the queue\", vbuf);\n"
        "\t\t\tk_fifo_get(&data->fifo_in, K_NO_WAIT);\n"
        "\t\t}\n",
        "\t\tif (ret == UVC_VBUF_DONE) {\n"
        "\t\t\tLOG_DBG(\"Video buffer %p transferred, removing from the queue\", vbuf);\n"
        "\t\t\tvbuf = k_fifo_get(&data->fifo_in, K_NO_WAIT);\n"
        "\t\t\tuvc_return_vbuf(dev, vbuf);\n"
        "\t\t}\n",
        "uvc return after fifo removal",
    )

    src = replace_once(
        src,
        "static void uvc_update(struct usbd_class_data *const c_data, const uint8_t iface,\n"
        "\t\t       const uint8_t alternate)\n"
        "{\n"
        "\tLOG_DBG(\"Select alternate %u for interface %u\", alternate, iface);\n"
        "}\n",
        "static void uvc_update(struct usbd_class_data *const c_data, const uint8_t iface,\n"
        "\t\t       const uint8_t alternate)\n"
        "{\n"
        "\tconst struct device *dev = usbd_class_get_private(c_data);\n"
        "\tstruct uvc_data *data = dev->data;\n\n"
        "\tLOG_DBG(\"Select alternate %u for interface %u\", alternate, iface);\n\n"
        "\tif (alternate == 0) {\n"
        "\t\tatomic_set_bit(&data->state, UVC_STATE_PAUSED);\n"
        "\t\tuvc_reset_queued_vbufs(dev);\n"
        "\t} else {\n"
        "\t\tatomic_clear_bit(&data->state, UVC_STATE_PAUSED);\n"
        "\t\tuvc_flush_queue(dev);\n"
        "\t}\n"
        "}\n",
        "uvc alternate setting pause",
    )

    src = replace_once(
        src,
        "static int uvc_enqueue(const struct device *dev, struct video_buffer *const vbuf)\n"
        "{\n"
        "\tstruct uvc_data *data = dev->data;\n\n"
        "\tk_fifo_put(&data->fifo_in, vbuf);\n",
        "static int uvc_enqueue(const struct device *dev, struct video_buffer *const vbuf)\n"
        "{\n"
        "\tstruct uvc_data *data = dev->data;\n\n"
        "\tif (atomic_test_bit(&data->state, UVC_STATE_PAUSED)) {\n"
        "\t\tuvc_return_vbuf(dev, vbuf);\n"
        "\t\treturn 0;\n"
        "\t}\n\n"
        "\tk_fifo_put(&data->fifo_in, vbuf);\n",
        "uvc enqueue while paused",
    )

    src = replace_once(
        src,
        "\t} else {\n"
        "\t\tatomic_set_bit(&data->state, UVC_STATE_PAUSED);\n"
        "\t}\n\n"
        "\treturn 0;\n"
        "}\n",
        "\t} else {\n"
        "\t\tatomic_set_bit(&data->state, UVC_STATE_PAUSED);\n"
        "\t\tuvc_return_queued_vbufs(dev);\n"
        "\t}\n\n"
        "\treturn 0;\n"
        "}\n",
        "uvc set stream stop returns queued buffers",
    )

    return src


def patch_ra_udc(src: str) -> str:
    return replace_once(
        src,
        "\t\tudc_submit_ep_event(dev, buf, 0);\n"
        "\t}\n\n"
        "\treturn;\n",
        "\t\tudc_submit_ep_event(dev, buf, 0);\n"
        "\t\tudc_event_xfer_next(dev, ep);\n"
        "\t}\n\n"
        "\treturn;\n",
        "renesas ra udc queue progression",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--zephyr-base", required=True)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    zephyr_base = Path(args.zephyr_base)
    out_dir = Path(args.out_dir)

    files = [
        (
            zephyr_base / "subsys/usb/device_next/class/usbd_uvc.c",
            out_dir / "subsys/usb/device_next/class/usbd_uvc.c",
            patch_uvc,
        ),
        (
            zephyr_base / "drivers/usb/udc/udc_renesas_ra.c",
            out_dir / "drivers/usb/udc/udc_renesas_ra.c",
            patch_ra_udc,
        ),
    ]

    for source, dest, patch in files:
        if not source.is_file():
            raise SystemExit(f"{source}: required Zephyr override source not found")
        try:
            text = source.read_text()
        except OSError as exc:
            raise SystemExit(f"{source}: failed to read Zephyr override source: {exc}") from exc

        patched = add_provenance_banner(patch(text), source)
        dest.parent.mkdir(parents=True, exist_ok=True)
        try:
            dest.write_text(patched)
        except OSError as exc:
            raise SystemExit(f"{dest}: failed to write generated override source: {exc}") from exc


if __name__ == "__main__":
    main()
